### ISSUE TITLE
please attribute the license of files copy/pasted

### ISSUE THREAD

**Issue by codefromthecrypt** [thundra-io/thundra-trace-chart#1]
Hi! It is on one hand good to extend software, and was nice to cite this had to do with zipkin-lens.

There's one thing that should be fixed though. Files seem to have been completely copy/pasted, but the apache license terms of the project haven't been cited anywhere. I'd recommend adding a LICENSE file noting that this contains modified version of zipkin lens, licensed under ASL 2.0

Make sense?

**Comment by milkersarac** [comment]
Hi, thank you for pointing out. I added the `LICENSE` file. I hope that makes sense.

**Comment by codefromthecrypt** [comment]
this looks like how we would have addressed the same. thanks!
